
server:
  port: 8081
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    exchange:
      producer: ex.producer.mgr
    routing-key:
      producer: rk.producer.mgr
    deadletter:
      producer: dl.producer.mgr
